on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  prepare:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ''
          draft: true
          prerelease: false
      - name: Record upload URL
        run: echo -n "${{ steps.create_release.outputs.upload_url }}" > release-upload-url.txt
      - name: Share upload URL
        uses: actions/upload-artifact@v1
        with:
          name: release-upload-url
          path: release-upload-url.txt

  unix:
    name: Upload Unix artifacts
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Pick up upload URL
        uses: actions/download-artifact@v1
        with:
          name: release-upload-url
      - name: Export Upload URL
        run: |
          echo "::set-env name==release_upload_url::$(cat release-upload-url.txt)"
          rm release-upload-url.txt

      - name: Fake artifact
        run: |
          date > foo.txt
          tar -czvf foo.tar.gz foo.txt

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.release_upload_url }} 
          asset_path: ./foo.tar.gz
          asset_name: foo.tar.gz
          asset_content_type: application/tar+gzip   
